Added initial image listing endpoint
Metatavu/oss-surveys-api-spec pull request #45
Opened 2024-03-07 12:40 UTC by villejuutila

Resolves #44

2024-03-07 13:05 UTC, anttileppa requested changes

2024-03-07 13:05 UTC, anttileppa commented on swagger.yaml
> +                  $ref: "#/components/schemas/Image"
```suggestion
                  $ref: "#/components/schemas/MediaFile"
```

2024-03-07 13:05 UTC, anttileppa commented on swagger.yaml
> +  /v1/images:
images -> mediaFiles

2024-03-07 13:05 UTC, anttileppa commented on swagger.yaml
> +      tags:
Add mandatory parameter "path"

2024-03-07 13:30 UTC, villejuutila commented on swagger.yaml
> +                  $ref: "#/components/schemas/Image"
Resolved.

2024-03-07 13:30 UTC, villejuutila commented on swagger.yaml
> +  /v1/images:
Resolved.

2024-03-07 13:31 UTC, villejuutila commented on swagger.yaml
> +      tags:
Resolved.

2024-03-13 07:31 UTC, anttileppa approved these changes

2024-03-13 07:31 UTC, merged